create table calcados (
	cod_calcado INT PRIMARY KEY,
	tamanho INT,
	tipo VARCHAR(15),
	cor VARCHAR(9),
	preco DECIMAL(5,2)
);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (1, 42, 'Bota Masculina', 'Azul', 384.66);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (2, 45, 'Sapato', 'Verde', 462.72);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (3, 33, 'Tênis Esportivo', 'Vermelho', 380.97);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (4, 48, 'Tênis Casual', 'Preto', 357.37);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (5, 33, 'Bota Masculina', 'Branco', 330.92);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (6, 41, 'Tênis Esportivo', 'Rosa', 345.98);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (7, 44, 'Tênis Esportivo', 'Camuflado', 420.77);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (8, 31, 'Tênis Esportivo', 'Roxo', 242.79);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (9, 44, 'Sandália', 'Cinza', 386.34);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (10, 48, 'Sandália', 'Marrom', 104.33);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (11, 39, 'Bota Feminina', 'Azul', 120.17);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (12, 32, 'Tênis Esportivo', 'Verde', 34.55);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (13, 35, 'Tênis Esportivo', 'Vermelho', 488.52);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (14, 35, 'Tênis Esportivo', 'Preto', 250.75);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (15, 33, 'Bota Feminina', 'Branco', 203.15);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (16, 30, 'Chinelo', 'Rosa', 232.77);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (17, 32, 'Bota Feminina', 'Camuflado', 169.38);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (18, 48, 'Chinelo', 'Roxo', 196.8);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (19, 47, 'Bota Masculina', 'Cinza', 425.85);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (20, 31, 'Chinelo', 'Marrom', 85.85);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (21, 48, 'Bota Masculina', 'Azul', 287.38);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (22, 42, 'Bota Masculina', 'Verde', 338.78);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (23, 38, 'Bota Masculina', 'Vermelho', 59.12);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (24, 38, 'Tênis Esportivo', 'Preto', 363.36);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (25, 46, 'Tênis Esportivo', 'Branco', 344.16);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (26, 27, 'Tênis Esportivo', 'Rosa', 102.07);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (27, 48, 'Chinelo', 'Camuflado', 173.83);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (28, 26, 'Tênis Esportivo', 'Roxo', 178.5);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (29, 36, 'Chinelo', 'Cinza', 362.03);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (30, 48, 'Chinelo', 'Marrom', 490.94);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (31, 40, 'Tênis Esportivo', 'Azul', 490.56);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (32, 31, 'Tênis Casual', 'Verde', 301.28);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (33, 44, 'Bota Masculina', 'Vermelho', 149.04);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (34, 40, 'Tênis Casual', 'Preto', 260.08);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (35, 45, 'Sapato', 'Branco', 118.75);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (36, 48, 'Bota Masculina', 'Rosa', 468.54);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (37, 36, 'Bota Feminina', 'Camuflado', 466.75);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (38, 39, 'Chinelo', 'Roxo', 298.2);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (39, 40, 'Bota Feminina', 'Cinza', 264.65);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (40, 42, 'Tênis Esportivo', 'Marrom', 177.88);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (41, 42, 'Tênis Esportivo', 'Azul', 180.96);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (42, 34, 'Sapato', 'Verde', 134.07);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (43, 30, 'Tênis Casual', 'Vermelho', 214.72);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (44, 33, 'Tênis Casual', 'Preto', 198.16);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (45, 35, 'Tênis Esportivo', 'Branco', 263.94);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (46, 31, 'Tênis Esportivo', 'Rosa', 416.79);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (47, 29, 'Chinelo', 'Camuflado', 450.43);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (48, 32, 'Chinelo', 'Roxo', 284.36);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (49, 36, 'Bota Masculina', 'Cinza', 257.84);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (50, 45, 'Bota Masculina', 'Marrom', 387.27);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (51, 45, 'Tênis Esportivo', 'Azul', 480.26);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (52, 33, 'Sapato', 'Verde', 438.39);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (53, 29, 'Chinelo', 'Vermelho', 117.83);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (54, 46, 'Chinelo', 'Preto', 114.27);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (55, 33, 'Chinelo', 'Branco', 181.48);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (56, 30, 'Chinelo', 'Rosa', 57.09);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (57, 36, 'Tênis Casual', 'Camuflado', 278.96);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (58, 27, 'Tênis Esportivo', 'Roxo', 286.49);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (59, 36, 'Bota Masculina', 'Cinza', 76.26);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (60, 27, 'Sandália', 'Marrom', 206.95);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (61, 45, 'Bota Masculina', 'Azul', 359.07);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (62, 37, 'Tênis Casual', 'Verde', 192.36);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (63, 39, 'Sapato', 'Vermelho', 472.44);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (64, 43, 'Bota Masculina', 'Preto', 277.48);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (65, 46, 'Bota Feminina', 'Branco', 329.32);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (66, 31, 'Bota Masculina', 'Rosa', 473.67);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (67, 37, 'Sapato', 'Camuflado', 262.62);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (68, 35, 'Bota Masculina', 'Roxo', 234.6);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (69, 27, 'Chinelo', 'Cinza', 46.67);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (70, 41, 'Tênis Casual', 'Marrom', 60.62);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (71, 39, 'Bota Masculina', 'Azul', 157.44);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (72, 41, 'Bota Feminina', 'Verde', 377.68);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (73, 29, 'Tênis Casual', 'Vermelho', 274.21);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (74, 43, 'Bota Feminina', 'Preto', 132.36);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (75, 41, 'Tênis Casual', 'Branco', 489.97);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (76, 28, 'Chinelo', 'Rosa', 411.28);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (77, 30, 'Bota Feminina', 'Camuflado', 405.77);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (78, 38, 'Sapato', 'Roxo', 271.71);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (79, 43, 'Tênis Casual', 'Cinza', 151.85);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (80, 40, 'Sandália', 'Marrom', 461.4);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (81, 46, 'Sapato', 'Azul', 61.65);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (82, 43, 'Tênis Casual', 'Verde', 22.79);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (83, 40, 'Sapato', 'Vermelho', 150.51);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (84, 28, 'Chinelo', 'Preto', 149.37);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (85, 39, 'Tênis Esportivo', 'Branco', 103.24);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (86, 26, 'Bota Feminina', 'Rosa', 421.47);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (87, 37, 'Sandália', 'Camuflado', 287.61);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (88, 45, 'Bota Feminina', 'Roxo', 495.18);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (89, 45, 'Chinelo', 'Cinza', 143.58);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (90, 37, 'Tênis Esportivo', 'Marrom', 498.88);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (91, 43, 'Sandália', 'Azul', 414.07);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (92, 31, 'Bota Masculina', 'Verde', 129.42);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (93, 28, 'Tênis Esportivo', 'Vermelho', 301.91);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (94, 41, 'Tênis Casual', 'Preto', 63.34);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (95, 44, 'Tênis Casual', 'Branco', 59.42);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (96, 31, 'Sandália', 'Rosa', 111.23);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (97, 45, 'Sapato', 'Camuflado', 283.51);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (98, 29, 'Bota Masculina', 'Roxo', 340.32);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (99, 36, 'Tênis Esportivo', 'Cinza', 481.87);
insert into calcados (cod_calcado, tamanho, tipo, cor, preco) values (100, 44, 'Chinelo', 'Marrom', 138.9);
