create table cliente (
	cod_cliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(23)
);
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (1, 'Kara-lynn Danis', 'F', '1983-10-17', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (2, 'Kara-lynn Ben', 'F', '1971-04-12', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (3, 'Justina Tidbury', 'F', '1991-12-17', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (4, 'Gasparo Vecard', 'M', '1951-03-01', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (5, 'Corilla Wigg', 'F', '2003-08-19', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (6, 'Jemie Greensall', 'F', '1962-03-29', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (7, 'Morissa Earwaker', 'F', '1978-01-11', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (8, 'Francisco Chadburn', 'M', '1965-01-25', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (9, 'Ernestus Dabels', 'M', '1953-04-01', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (10, 'Gabriella Francesconi', 'F', '1949-01-21', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (11, 'Caddric Healings', 'M', '1981-11-20', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (12, 'Angie Mineghelli', 'F', '2001-02-01', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (13, 'Carmel MacKaig', 'F', '1983-07-06', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (14, 'Dynah Canon', 'F', '1981-03-22', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (15, 'Levon Pinyon', 'M', '1970-12-16', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (16, 'Kevon Rhubottom', 'M', '1985-09-20', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (17, 'Tim Pressland', 'F', '1976-07-23', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (18, 'Colline Deerr', 'F', '1959-12-07', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (19, 'Devy Sainsbury', 'M', '1959-09-16', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (20, 'Alano Fiske', 'M', '1945-08-12', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (21, 'Clemmie Le Noire', 'F', '1999-07-23', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (22, 'Normie Burel', 'M', '1943-12-30', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (23, 'Jarib McEnhill', 'M', '1963-05-29', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (24, 'Abram Jaggers', 'M', '1953-04-29', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (25, 'Sela Tesoe', 'F', '1961-08-30', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (26, 'Fabian Kuhnt', 'M', '1995-07-29', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (27, 'Esmeralda Milkeham', 'F', '1948-05-03', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (28, 'Idell Maskelyne', 'F', '1954-11-04', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (29, 'Eleonore Gellier', 'F', '1963-02-16', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (30, 'Vi Alltimes', 'F', '1995-03-09', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (31, 'Sutherland Row', 'M', '1959-06-02', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (32, 'Zenia Wile', 'F', '2002-09-22', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (33, 'Caitlin Laing', 'F', '1970-03-02', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (34, 'Ailey Teresse', 'F', '1996-08-19', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (35, 'Phil Goodliffe', 'M', '2003-06-08', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (36, 'Abbott Yellowley', 'M', '2003-12-04', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (37, 'Moselle Jori', 'F', '1969-05-27', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (38, 'Anita Haymes', 'F', '1965-11-08', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (39, 'Madelin Boole', 'F', '1951-01-28', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (40, 'Phillie Loblie', 'F', '1941-08-03', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (41, 'Kelsy Costy', 'F', '1943-03-22', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (42, 'Keary Clulow', 'M', '1965-10-12', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (43, 'Mariya Langham', 'F', '1965-09-29', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (44, 'Aggy Groundwator', 'F', '1953-03-06', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (45, 'Bancroft Shire', 'M', '1976-02-12', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (46, 'Isabel McReath', 'F', '1969-07-08', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (47, 'Brena Mewis', 'F', '1986-11-07', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (48, 'Luella Uppett', 'F', '1971-08-16', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (49, 'Erda Burdus', 'F', '2003-05-30', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (50, 'Rhianna Slobom', 'F', '1995-08-07', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (51, 'Malanie Oxley', 'F', '1965-06-01', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (52, 'Harri Follin', 'F', '1987-07-26', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (53, 'Fonsie Cochet', 'M', '1980-03-31', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (54, 'Shalom Naile', 'M', '1943-11-03', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (55, 'Saxon Salmond', 'M', '1956-03-27', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (56, 'Rice Sturmey', 'M', '1966-08-09', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (57, 'Jerrome Portsmouth', 'M', '2001-04-16', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (58, 'Corilla Arnould', 'F', '1957-08-21', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (59, 'Adina McGraith', 'F', '1977-12-24', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (60, 'Sky Yakobovitz', 'M', '1996-11-23', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (61, 'Steffane Eisak', 'F', '1990-07-22', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (62, 'Keen Feckey', 'M', '1999-06-18', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (63, 'Melamie Lapworth', 'F', '1996-11-28', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (64, 'Zacharie Flori', 'M', '1962-07-28', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (65, 'Dieter Hasselby', 'M', '1971-01-23', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (66, 'Carie Carlyon', 'F', '1976-01-14', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (67, 'Gerda Beeck', 'F', '1947-05-30', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (68, 'Garrick Regan', 'M', '1999-04-21', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (69, 'Yance Nurdin', 'M', '1982-11-01', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (70, 'Westleigh Mounsey', 'M', '1972-01-11', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (71, 'Dilan Enocksson', 'M', '1977-02-13', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (72, 'Brodie Duggan', 'M', '1958-03-22', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (73, 'Maje Baelde', 'M', '1991-07-12', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (74, 'Emiline Mulvey', 'F', '1982-05-08', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (75, 'Isabella Whylie', 'F', '1991-10-28', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (76, 'Charmine Meekin', 'F', '1946-02-16', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (77, 'Henrik Islep', 'M', '1945-12-02', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (78, 'Gerta Heaviside', 'F', '1964-04-25', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (79, 'Verge Wharram', 'M', '1981-11-17', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (80, 'Marian Bowich', 'F', '1959-10-09', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (81, 'Shelton Edgecumbe', 'M', '1968-09-21', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (82, 'Karlis Norker', 'M', '1953-05-19', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (83, 'Alessandra Lacky', 'F', '1973-01-04', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (84, 'Derwin Kingsnorth', 'M', '1954-09-19', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (85, 'Lainey Craufurd', 'F', '1994-02-26', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (86, 'Rosemarie Ellerman', 'F', '1940-05-11', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (87, 'Cooper Bragginton', 'M', '1969-10-29', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (88, 'Shirlene Gilhespy', 'F', '1996-01-28', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (89, 'Marquita Welland', 'F', '1999-09-04', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (90, 'Vi Caldroni', 'F', '1953-10-03', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (91, 'Hyacinthia Morman', 'F', '2001-07-20', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (92, 'Cristi Pietruschka', 'F', '1952-01-19', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (93, 'Marlin Jeannot', 'M', '1980-07-20', 'Vince e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (94, 'Alena Brabender', 'F', '1978-08-06', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (95, 'Liana Klessmann', 'F', '1989-06-19', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (96, 'Kennie Walpole', 'M', '1965-07-07', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (97, 'Feodor Shreenan', 'M', '2000-10-05', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (98, 'Merl Dady', 'F', '1981-04-07', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (99, 'Bay Darby', 'M', '1978-12-27', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (100, 'Trudey Gard', 'F', '2003-12-07', 'Vila Operária');
